apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${NAMEPREFIX}-system
resources:
- ../../config/namespace
- ../ironic

configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap
- behavior: create
  envs:
  - ironic-htpasswd
  name: ironic-htpasswd
- behavior: create
  envs:
  - ironic-inspector-htpasswd
  name: ironic-inspector-htpasswd

secretGenerator:
- literals:
  - password=changeme
  name: mariadb-password
  type: Opaque
- name: ironic-auth-config
  files:
  - auth-config=ironic-auth-config
- name: ironic-inspector-auth-config
  files:
  - auth-config=ironic-inspector-auth-config
- name: ironic-rpc-auth-config
  files:
  - auth-config=ironic-rpc-auth-config

patchesStrategicMerge:
- keepalived_patch.yaml
- auth.yaml
